### ISSUE TITLE
how is serviceaccountkey read?

### ISSUE THREAD

**Issue by mephmanx** [dubinsky/cloud-run#11]
I am getting this error trying to use this plugin 

Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1404)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.api.client.json.gson.GsonParser.nextToken(GsonParser.java:149)
	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:213)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:358)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromStream(ServiceAccountCredentials.java:496)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromStream(ServiceAccountCredentials.java:475)
	at org.podval.tools.cloudrun.CloudRun.<init>(CloudRun.scala:21)
	at org.podval.tools.cloudrun.CloudRunService.<init>(CloudRunService.scala:15)
	at org.podval.tools.cloudrun.CloudRunTask.cloudRunService(CloudRunTask.scala:17)
	at org.podval.tools.cloudrun.CloudRunPlugin$DeployTask.execute(CloudRunPlugin.scala:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)

It looks like it is related to service account key.  I am saving the json key in a file called google.key at the root level of the project.  I have it loaded from a secret on GitHub Actions.  Im not sure how to tell it to use that....

**Comment by dubinsky** [comment]
Plugin reads the service account key from a property; this [section](https://github.com/dubinsky/cloud-run#service-account-key-property) of the README describes the default name of this property (`gcloudServiceAccountKey`) and how to change it. The property needs to be set - one way or the other - to the _content_ of the JSON key file.

**Comment by mephmanx** [comment]
ok, thank you.  I think I figured that out but now I am getting this error...

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "annotations$1" is null
	at org.podval.tools.cloudrun.ServiceExtender$.addAnnotationsTo$$anonfun$1(ServiceExtender.scala:64)
	at scala.collection.immutable.Map$Map3.foreach(Map.scala:448)
	at org.podval.tools.cloudrun.ServiceExtender$.addAnnotationsTo(ServiceExtender.scala:64)
	at org.podval.tools.cloudrun.ServiceExtender$.addAnnotations$$anonfun$1(ServiceExtender.scala:21)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at org.podval.tools.cloudrun.ServiceExtender$.update(ServiceExtender.scala:31)
	at org.podval.tools.cloudrun.ServiceExtender$.addAnnotations(ServiceExtender.scala:21)
	at org.podval.tools.cloudrun.CloudRunService.deploy(CloudRunService.scala:46)
	at org.podval.tools.cloudrun.CloudRunPlugin$DeployTask.execute(CloudRunPlugin.scala:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by mephmanx** [comment]
Here is the repo, its the deploy branch

https://github.com/dotcomrow/cloud-run-example.git

**Comment by dubinsky** [comment]
Did you try replacing the placeholders in the `service.yaml`  ([line 4](https://github.com/dotcomrow/cloud-run-example/blob/deploy/service.yaml#L4), [line 9](https://github.com/dotcomrow/cloud-run-example/blob/deploy/service.yaml#L9)) file with valid values?

**Comment by mephmanx** [comment]
yeah, they are replaced during the actions build.  They are there, I checked.

**Comment by dubinsky** [comment]
It seems that Kubernetes  metadata is null in your case; it would help if you ran the plugin in debugger and looked at the data... In the meantime, I'll release a version of the plugin that does not assume non-nullness in this case.

**Comment by mephmanx** [comment]
ok, ill try.  Thank you

**Comment by mephmanx** [comment]
is the annotations block needed in metadata?

**Comment by dubinsky** [comment]
> is the annotations block needed in metadata?

No, it is optional... But I never saw metadata without it.

Version 0.3.2 of the plugin is on the Gradle Plugin Portal; this version no longer assumes that annotations are present.

**Comment by mephmanx** [comment]
ok, Ill give it a try.  Thanks.  Im not familiar with Scala and honestly not a grade expert either....couldent really figure out how to run it in debug to get anything useful out of it...

**Comment by mephmanx** [comment]
hmmm...seeing this now...

	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.IllegalStateException: You are currently running with version 2.1.1 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Cloud Run Admin API library.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
	at com.google.api.client.util.Preconditions.checkState(Preconditions.java:113)
	at com.google.api.services.run.v1.CloudRun.<clinit>(CloudRun.java:44)
	... 150 more

**Comment by dubinsky** [comment]
Version 0.3.4 of the plugin is on the Gradle Plugin Portal; this version updates some Google dependencies.

**Comment by dubinsky** [comment]
I am not sure how is [appengine-gradle-plugin](https://github.com/dotcomrow/cloud-run-example/blob/deploy/build.gradle#L8
) used in your project; if it is not, it's best to try without it, since there _may_ be some Google dependency conflicts between that plugin and mine...

**Comment by dubinsky** [comment]
Are you using version 0.3.4 of my plugin?  In 0.3.4, that dependency is of a different version...

**Comment by mephmanx** [comment]
Ah, I think I am using 0.3.2, will update now.  Thank you!

**Comment by dubinsky** [comment]
Hmm... Looks like the whole metadata is missing, not just annotations...
I published version 0.3.5 that checks for this null also.
Was this service ever deployed or is this a new deployment?
Did you try running Gradle task `cloudRunDescribe`/`cloudRunDescribeRevision`?

**Comment by mephmanx** [comment]
new deployment.  I am creating a example template to use for future reference in creating more microservices.

**Comment by mephmanx** [comment]
got this now:

Caused by: java.lang.NullPointerException: Cannot invoke "com.google.api.services.run.v1.model.ObjectMeta.setName(String)" because the return value of "com.google.api.services.run.v1.model.RevisionTemplate.getMetadata()" is null
	at org.podval.tools.cloudrun.ServiceExtender$.setRevisionName$$anonfun$1(ServiceExtender.scala:27)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at org.podval.tools.cloudrun.ServiceExtender$.update(ServiceExtender.scala:31)
	at org.podval.tools.cloudrun.ServiceExtender$.setRevisionName(ServiceExtender.scala:27)
	at org.podval.tools.cloudrun.CloudRunService.deploy(CloudRunService.scala:49)
	at org.podval.tools.cloudrun.CloudRunPlugin$DeployTask.execute(CloudRunPlugin.scala:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)

**Comment by mephmanx** [comment]
I didnt try running those 2 commands....I had it set up to only connect to google in github actions.  I can pull down creds and give it a try.

**Comment by mephmanx** [comment]
I see what you mean....its weird that its not finding the name...   unless its not reading the service.yaml file I provided...  It looked like it found it locally, I did get an error when the file did not exist which went away when I created it so I thought it was right...

Configuring it like this:

cloudRun {
  region = 'us-east1'                                     // required
  serviceYamlFilePath = "$rootDir/service.yaml"     // optional
}

**Comment by dubinsky** [comment]
I am not sure at this point *what* isn't it finding :(
It may be easier to see what's what if you reconfigured the project to deploy locally, not from GitHub, but for now I published version 0.3.6 of the plugin that prints out the location and the content of the YAML file describing the service. Please try it - maybe we'll see something...
Thank you for debugging this issue!

**Comment by mephmanx** [comment]
it looks like that did it.  I added the metadata under the spec.template block and updated the plugin and i saw more logging and it looks like it deployed!  Thank you for your prompt help!  Ill open a new issue if I notice anything else.

**Comment by mephmanx** [comment]
let me know which metadata you want to keep, I can help with further debugging.

**Comment by mephmanx** [comment]
if I took the metadata from the yaml generator on the gcp console and put it in the file (for allowing all traffic vs only IAM authenticated traffic) would that work?  Ill try some things out now...

**Comment by dubinsky** [comment]
I will release shortly a version of my plugin that does not require _any_ metadata under `spec.template`, just as was in your original configuration. Anything that you do put there should affect the deployment, but nothing should be required.

Thanks for pin-pointing the issue! I'll close it once the fixed version is verified by you ;)

**Comment by dubinsky** [comment]
@mephmanx version 0.3.7 of the plugin is up at the Gradle Plugin Portal; it should work with or without the `spec.template.metadata` block in the YAML file. Thanks!

**Comment by mephmanx** [comment]
Confirmed, things work when I revert back to my original service.yaml file.  Great work!
